version: "3.9"
services:

  postgres:
    image: postgres:12.8-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=issues_4_missions
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:    
